<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
  <title>JabRef</title>
  <link href='/css/style.css' rel='stylesheet' type='text/css' />
</head>

<body>
  <div id="container">
    <?php include("../navigation.php"); ?>
    <a href="Contents.php">Back to contents</a>


    <h1>JabRef</h1>

    <p><strong>Note:</strong> The <em>bibtex</em> program is
    mentioned many times in these help files. <em>Bibtex</em> is a
    utility for the generation of bibliographic references in LaTeX
    documents, created by Oren Patashnik. The same database format
    is also used with CiteMaker, a utility for bibliography
    generation in Adobe FrameMaker.</p>

    <p>JabRef is is a program for working with <em>bibtex</em>
    databases. The program uses no internal file format, which
    means you normally load and save your databases directly in the
    <em>bibtex</em> .bib format. However, you can also import
    bibliography databases in a number of other formats into
    JabRef.</p>

    <p>JabRef provides sorting and searching functionality for
    getting the overview of your databases' contents. You can
    easily add new database entries without having to remember what
    information is required, and <em>bibtex</em> keys can be
    autogenerated. JabRef will be most useful for those using
    <em>bibtex</em> or CiteMaker, but may also be of use to those
    using other referencing systems or simply wanting to organize
    their literature sources.</p>

    <p><a href="BaseFrameHelp.php">The JabRef main window</a></p>
    <?php include("../footer.php"); ?>
  </div>

</body>
</html>
