<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
  <title>JabRef reference manager</title>
  <link href='css/style.css' rel='stylesheet' type='text/css' />
</head>

<body>
  <div id="container">

    <?php include("navigation.php"); ?>

    <div id="rightpanel">
      <h3 id="News">News</h3>

      <div class="item">
        June 28th, 2007
      </div>

      <div class="item_desc">
        Version 2.3beta
      </div>

      <div class="item">
        January 30th, 2007
      </div>

      <div class="item_desc">
        Version 2.2
      </div>

      <div class="item">
        November 26th, 2006
      </div>

      <div class="item_desc">
        Version 2.2beta2
      </div>

      <div class="item">
        October 13th, 2006
      </div>

      <div class="item_desc">
        Version 2.2beta
      </div>

      <div class="item">
        August 9th, 2006
      </div>

      <div class="item_desc">
        Version 2.1
      </div>

      <div class="item">
        June 29th, 2006
      </div>

      <div class="item_desc">
        Version 2.1beta2
      </div>

      <div class="item">
        May 9th, 2006
      </div>

      <div class="item_desc">
        Version 2.1beta
      </div>

      <div class="item">
        February 2nd, 2006
      </div>

      <div class="item_desc">
        Version 2.0.1
      </div>

      <div class="item">
        January 30th, 2006
      </div>

      <div class="item_desc">
        Version 2.0
      </div>

      <div class="item">
        January 15th, 2006
      </div>

      <div class="item_desc">
        Version 2.0beta2
      </div>

      <div class="item">
        January 4th, 2006
      </div>

      <div class="item_desc">
        Version 2.0beta
      </div>

      <div class="item">
        September 15th, 2005
      </div>

      <div class="item_desc">
        Version 1.8.1
      </div>

      <div class="item">
        July 30th, 2005
      </div>

      <div class="item_desc">
        Version 1.8
      </div>

      <div class="item">
        July 13th, 2005
      </div>

      <div class="item_desc">
        Version 1.8beta2
      </div>

      <div class="item">
        June 6th, 2005
      </div>

      <div class="item_desc">
        Version 1.8beta
      </div>
    </div>

    <div id="main">
      <h3 id="about">About</h3>

      <p><acronym>JabRef</acronym> is an open source
      bibliography reference manager. The native file format used
      by <acronym><span class="red">J</span><span class=
      "orange">ab</span>Ref</acronym> is <acronym>BibTeX</acronym>,
      the standard <acronym>LaTeX</acronym> bibliography format.
      <acronym><span class="red">J</span><span class=
      "orange">ab</span>Ref</acronym> runs on the Java VM (version
      1.4.2 or greater), and should work equally well on Windows,
      Linux and Mac OS X.</p>

      <p>BibTeX is an application and a bibliography file format
      written by Oren Patashnik and Leslie Lamport for the LaTeX
      document preparation system. <a href=
      "http://www.ecst.csuchico.edu/~jacobsd/bib/formats/bibtex.html">
      General information about BibTeX</a>.</p>

      <p>Bibliographies generated by LaTeX and BibTeX from a BibTeX
      file can be formatted to suit any reference list
      specifications through the use of different BibTeX style
      files. We support this initiative to build a searchable
      database of BibTeX style files, organized by journal names:
      <a href="http://jo.irisson.free.fr/bstdatabase/">LaTeX
      bibliography style database</a>.</p>

      <p>You can run JabRef instantly with Java Web Start:
      <a href="http://jabref.sourceforge.net/jws/jabref.jnlp">Run JabRef.</a></p>

      <h3 id="features">Features</h3>

      <div class="features_column">

        <div class="feature">Advanced BibTeX editor</div>
        <div class="feature_desc">
	  Detailed editing of bibtex entries.
	</div>
	
	<div class="feature">Search functions</div>
        <div class="feature_desc">
          Search a pattern in the whole bibliography.
        </div>
	
	<div class="feature">Classification of entries</div>
        <div class="feature_desc">
          You can group entries explicitly, by keywords or any
          other fields.
        </div>
	
	<div class="feature">Import of various formats</div>
        <div class="feature_desc">
          BibTeXML, CSA, Refer/Endnote, ISI Web of Science,
          SilverPlatter, Medline/Pubmed (xml), Scifinder, OVID,
          INSPEC, Biblioscape, Sixpack, JStor and RIS.
        </div>
	
	<div class="feature">Built-in and custom export formats</div>
        <div class="feature_desc">
          HTML, Docbook, BibTeXML, MODS, RTF, Refer/Endnote and
          OpenOffice.org.
        </div>

        <div class="feature">Customization of BibTeX fields</div>
        <div class="feature_desc">
          You can add your own fields to any BibTeX entry type.
        </div>
	
	<div class="feature">Customization of the JabRef interface</div>
        <div class="feature_desc">
          Fonts, displayed fields, etc
        </div>
	
	<div class="feature">Integrates to your environment</div>
        <div class="feature_desc">
          Launch external applications: PDF/PS viewers, web
          browser, insert citations into LyX, Kile and WinEdt
        </div>
	
	<div class="feature">Automatic Key generation</div>
        <div class="feature_desc"></div>
	
	<div class="feature">Search Medline and Citeseer</div>
        <div class="feature_desc"></div>

      </div>
    </div>
    <?php include("footer.php"); ?>
  </div>

</body>
</html>
